language: rust
rust:
    - stable
    - beta
    - nightly
sudo: false
dist: trusty
os: linux
cache:
    directories:
        - $HOME/.cargo
        - target
env:
    global:
        - secure: "hrpQNYCQVQZu8Fem46jKa80UQsbj85BVO03MyBkM9+GdW+og4gSFKCt2S5m3Ac+7I5TXJSF4m6il1Z/eoydT/ISlVAw4MlKuouzChlhaA5dqkJJy1kGHRMgMJuc1HmKzVsLlvl8hZgtSGPwXjrVHZFYXa9/IFxCf0KD5r7Gv9Tmq8fNXI6pSamZnF3lN94JLjTKNCsUC/r0eccu1Nnfees/QqiCr4hRTyjKRiPyDnQqu5lYkZjaJqsMJQnagwqldk9VgixxQyYgYiPcMXdmA9DM5FJhtDUCHjyIwUxqf2FCtXSScwwAjjMMKTibmwZdvmZtLnVvwHtilGr7SbKeIGPqv/fsKms9AKUPmny3efu5Y5v3411tvSMJSUGd+PWpzqZVlaY0v4S7rAsf2BDlOpSHaXaujDvdAsO5bJHJeoQWpi9hItMZjM/TTCLfvttsln0LbDOuMvPYVrXMmABcoOcNPZKB1a/qqYAfR8cualX5kUPHSUCahAUPH3r9AzwT+BAovb2heLNwYMLa+Iv3T9vuceTkEijCAHTrYtChhNAUAlxA9YB/z/Qz7emfYq4Nbxv6dWzJuQIweM9p4KWefv9WMQXbkcIRrImcQetWailMIvtshvFwV6PC3JM3AXVhc/edEbPgv89Wd1osEqqLfV6O7lQvKXtzyHmI5wK8QcZQ="
        - secure: "bYatwjJXzDlY8lHsEPOZ7bgNpx9Mh2EMwujnhwQgWKMPsPJ8A10OsbsAh1rjpj5CbGH2m2y7zW454+ScQkQByQjledKSE8MYcp7ya3q2O0CErpQy5Vu72JojK4FIvS17mwn5vOZzVn1EI9K0QA8HzI2poAC0ISWcc/8pS8txrfDvkbwjvEtb3l4rz51aGl/9xqdp/9rv6mA544Mf6qVIONuKaIdZ0/m8Jqx+rsndf+9raDaRtPw+NByK/1Vl32F524a80EhJoKXvd1ymottX+jK0DQhLRBy8Ys3G9Ye6tA6usWx3Z7OYbiwnl6P2SftCRMI/lWtWCoVOUUI1BqQzZ2PLRxNj0KKZxP7jTKlaURa8GxdDCrj92vB2o/ou4WfLkXj1EmeBwKQfKQnxkm62KNVTwjUt8bhqmnq5wBGAwwutw8v85F+cEC0tLS98U7Vhwh6tM1N8NzL/C71ncFquXMZfu+Ctq9WGVETlJI8wZ0BAShI7cZcC87bpAiMe5jodPsUjJR20lRW+eHnISjf4aCOh3R46FATKIDvOL35U/59SFmd5A65KmJvJtHB8Tgg3KwZUWHjwmjMTkOi2Yiu3MLUTZspIY18SefgODlBp0kGou8QmaDkeoq9usGVt5rs9pwuPTCwNEM2CYqNJknmVW+3SjfL8CacvdnhDgD06V4s="
before_script:
    - curl -L https://github.com/arcnmx/ci/archive/master.tar.gz | tar -xzC $HOME && . $HOME/ci-master/src

script:
    - cargo build
    - cargo test

deploy:
    provider: script
    script: "true"
    on:
        tags: true
        all_branches: true
        condition: "$TRAVIS_RUST_VERSION = stable"

before_deploy:
    - cargo doc
    - cargo package

after_deploy:
    - cargo pages-publish
    - cargo publish
